# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 722ba9a9359d85eb5acd15c7da83a3bcaf9c872bf0e48df7f00f5272765c87eb6e73932b5545614324c8dcef458d72d1b80f33c699cc49c224a2bed8f23bde33

test:
  secret_key_base: 6594218db346a751a3522fbce506114b5e46cf72aec1c31d5e7de21be2fccebac8be0c496e11cb358196c467c90c530286f601beaaa917c3500e95fb11178652

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
